events {}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream contact_api {
        server contact-api:8000;
    }

    server {
        listen 80;
        server_name mafiabears.fr mafiabears.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name mafiabears.fr mafiabears.com;

        ssl_certificate /etc/letsencrypt/live/mafiabears.fr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mafiabears.fr/privkey.pem;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
        location /api/ {
            proxy_pass http://contact_api/;
        }
    }
}
